### ISSUE TITLE
Support Immutable values

### ISSUE THREAD

**Issue by XuluWarrior** [skortchmark9/reselect-devtools-extension#3]
Currently, if a selector outputs Immutable values these are shown in the state tree in their rawest object form e.g. `Immutable.Map({a:1})` becomes
```
{
  size : 1
 __altered : false
 _root:
  entries : [
   "a"
  ]
  ownerID: {}
}
```
rather than
```
{
  a : 1
}
```

**Comment by skortchmark9** [comment]
Hey @XuluWarrior thanks for the issue / PR - I don't think I have notifications set up properly for this repository. 

My feeling right now is that I'd prefer ```selectorGraph()``` to output pure a JSON dict (or string, if we need to) Any reason you decided to make the change in the extension rather than in the lib?

**Comment by skortchmark9** [comment]
Yeah I think I'm sold

**Comment by anikolaev** [comment]
Is it implemented? I still see internal structure of Immutable objects in Reselect Devtools Exension@0.0.2 + tools@^0.0.7.

**Comment by XuluWarrior** [comment]
It doesn't look like.  My PR hasn't been merged yet.

**Comment by anikolaev** [comment]
@XuluWarrior wasn't it decided to have this been fixed in the extension?

**Comment by XuluWarrior** [comment]
@anikolaev my PR (#4) is for the extension

**Comment by anikolaev** [comment]
@XuluWarrior Oh, I see now. I first thought you are the owner of the extension repo.

**Comment by anikolaev** [comment]
@skortchmark9 could we have this merged?

**Comment by skortchmark9** [comment]
Merged now. Sorry about the delay I've been doing other things.
