### ISSUE TITLE
Request to update repository with version 0.0.2 from Chrome App Store

### ISSUE THREAD

**Issue by hydrosquall** [skortchmark9/reselect-devtools-extension#8]
Hi @skortchmark9 ,

Thanks for the great work on this extension! I was wondering if you might be able to upload the source of the `v0.0.2` version of this extension to Github, which has some functionality that isn't in `v0.0.1`, like enabling highlighting of the most recomputed nodes, or counting the number of recomputations. (very useful features, by the way!)

I'm experimenting with some different graph layouts, and was hoping to work with the same version of the source code that's in the chrome extension store.

Thanks for your consideration!

**Comment by skortchmark9** [comment]
Awesome - yeah the graph layouts are quite bad right now. I'm planning to do some work on this stuff in the next week - sorry for being unresponsive.

**Comment by hydrosquall** [comment]
No worries at all! I ended up forking this repository, and made some progress trying some new Cytoscape layouts for an internal hackathon. I'll stay tuned for updates to this repository in case there's any changes that would make sense to share back upstream.

**Comment by skortchmark9** [comment]
Cool! I'd be very happy to take a patch if you've got one, the layout stuff has always bugged me.

**Comment by skortchmark9** [comment]
The original request was to merge the extension 0.0.2 branch to master, which has been done. @hydrosquall if you upstream your layout changes, please do so on a different issue. Thanks so much! It makes me happy to know other people are hacking on this :)
